Finocart.Web/Controllers/BankCompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finocart.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Finocart.Web;
using Finocart.CustomModel;
using Finocart.Services;
using System.IO;
using System.Net.Mail;
using Microsoft.IdentityModel.Protocols;
using System.Net;
using System.Configuration;
using Finocart.Model;
using Microsoft.Extensions.Configuration;
using System.Net.Http.Headers;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Finocart.Web.Views.Common;
using static Finocart.Web.Controllers.BaseController;
using Microsoft.AspNetCore.Hosting;
using System.Text;

namespace Finocart.Web.Controllers
{


    public class BankCompanyController : Controller
    {

        #region Interface declaration

        private readonly IBank _companyRepository;
        private readonly IAnchorCompany _AnchorCompanyRepository;
        private readonly IConfiguration _configuration;

        /// <summary>
        /// Common Repository
        /// </summary>
        private readonly ICommon _CommonRepository;
        /// <summary>
        /// Lookup data Repository
        /// </summary>
        private readonly ILookupDetails _lookUpRepository;

        private readonly IHostingEnvironment _hostingEnvironment;
        #endregion

        #region Constructor 

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="employeeRepository"></param>
        public BankCompanyController(IBank companyRepository, IAnchorCompany anchorCompanyRepository, ICommon CommonRepository, ILookupDetails lookupDetailsRepository, IConfiguration configuration, IHostingEnvironment hostingEnvironment)
        {
            _companyRepository = companyRepository;
            _AnchorCompanyRepository = anchorCompanyRepository;
            _CommonRepository = CommonRepository;
            _lookUpRepository = lookupDetailsRepository;
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        #endregion

        #region

        public IActionResult Index()
        {
            return View();
        }

        #endregion

        #region Bank Bashboard
        /// <summary>
        /// bank dashboard View
        /// </summary>
        /// <returns></returns>
        /// 
        [JWTAuthorize("Account", "UserLogin")]
        [CustomFilter]
        public IActionResult BankDashboard()
        {

            string ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            string ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            Int32? UserID = HttpContext.Session.GetInt32("UserID");
            string ErrorMessage = string.Empty;

            try
            {
                var Res = _CommonRepository.AuditTrailLog("Home", "BankDashboard", UserID, 0);
                string requestAmountReceiveToday = _companyRepository.GetRequestAmountReceivedToday();
                ViewBag.requestAmountReceiveToday = requestAmountReceiveToday;
                var start = "0";
                var length = "500";
                var sortBy = "CompanyID";
                var page = "";
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                var lstEmailIDofBank = _companyRepository.GetBankId(UserID);
                int Bankid = 0;
                var CompanyName = "";
                IEnumerable<BankAnchorListModel> cm = _companyRepository.GetBankSetLimitList(sortBy, pageSize, skip, CompanyName, "", 0);
                ViewData["TOTALNEWANCHOR"] = cm.Count();

                IEnumerable<BankLimitAnchorList> objexistingAnchor = _companyRepository.TotalExistingAnchor(sortBy, pageSize, skip, CompanyName, "").Distinct();
                ViewData["TOTALEXISTINGANCHOR"] = objexistingAnchor.Count();

                IEnumerable<BankLimitAnchorListView> objTotalBankLimitAnchorLists = _companyRepository.GetTotalBankLimitAnchorLists(sortBy, pageSize, skip, CompanyName, page, UserID);
                decimal? TotalSetBankLimit = 0;
                for (int i = 0; i < objTotalBankLimitAnchorLists.Count(); i++)
                {
                    TotalSetBankLimit = Sum(TotalSetBankLimit, objTotalBankLimitAnchorLists.ElementAt(i).Available_Limits);

                }
                String temp3 = String.Format("{0:C0}", TotalSetBankLimit);
                temp3 = temp3.Replace("$", "");
                if (Convert.ToString(TotalSetBankLimit).Contains("."))
                {
                    string[] values2 = Convert.ToString(TotalSetBankLimit).Split('.');

                    ViewData["TOTALBANKLIMITANCHORLIST"] = temp3;
                }
                else
                {
                    ViewData["TOTALBANKLIMITANCHORLIST"] = temp3;
                }

                IEnumerable<BankLimitAnchorListView> objUtilizeBankLimitAnchorLists = _companyRepository.GetTotalBankLimitAnchorLists(sortBy, pageSize, skip, CompanyName, page, UserID);
                decimal? objTotalUtilizeBankLimit = 0;
                for (int i = 0; i < objTotalBankLimitAnchorLists.Count(); i++)
                {
                    objTotalUtilizeBankLimit = Sum(objTotalUtilizeBankLimit, objUtilizeBankLimitAnchorLists.ElementAt(i).Utilized_Limits);

                }
                String temp2 = String.Format("{0:C0}", objTotalUtilizeBankLimit);
                temp2 = temp2.Replace("$", "");
                if (temp2.Contains("."))
                {
                    string[] values2 = Convert.ToString(objTotalUtilizeBankLimit).Split('.');

                    ViewData["TOTALUTILIZEDBANKLIMIT"] = temp2;
                }
                else
                {
                    ViewData["TOTALUTILIZEDBANKLIMIT"] = temp2;
                }
                IEnumerable<TotalPendingKYC> objpendingKyc = _companyRepository.GetTotalCompanyPendingKYCs();
                ViewData["TOTALPENDINGKYC"] = objpendingKyc.Count();
            }
            catch (Exception ex)
            {
                var st = new StackTrace(ex, true);
                var frame = st.GetFrame(0);
                int ErrorLine = frame.GetFileLineNumber();
                var Result = _CommonRepository.LogManagement(ControllerName, ActionName, ex.Message, ErrorLine, UserID);
                return RedirectToAction("ErrorPage", "Common");
            }

            return View("Dashboard");
        }
        public static decimal? Sum(decimal? num1, decimal? num2)
        {
            decimal? total;
            total = num1 + num2;
            return total;
        }
        #endregion

        #region Get Top Anchor Company
        /// <summary>
        /// list display top anchor
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetTopAnchorData()
        {
            string ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            string ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            Int32? UserID = HttpContext.Session.GetInt32("UserID");
            string ErrorMessage = string.Empty;
            try
            {
                var Res = _CommonRepository.AuditTrailLog("Home", "Top Anchor Data", UserID, 0);
                int BankID = Convert.ToInt32(UserID);
                string Role = HttpContext.Session.GetString("Role");
                var draw = Request.Form["draw"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                int? recordsFiltered = 0;
                int? recordsTotal = 0;
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                var sortBy = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault() + " " + Request.Form["order[0][dir]"].FirstOrDefault();
                IEnumerable<TopAnchorCompaniesInBankDashboardModel> cm = _companyRepository.GetTopAnchor(sortBy, pageSize, skip, BankID);

                if (cm != null && cm.Count() != 0)
                {
                    recordsFiltered = cm.ElementAt(0).FilteredRecord;
                    recordsTotal = cm.ElementAt(0).TotalRecord;
                }

                return Json(new { draw = draw, recordsFiltered = recordsFiltered, recordsTotal = recordsTotal, data = cm });
            }
            catch (Exception ex)
            {
                var st = new StackTrace(ex, true);
                var frame = st.GetFrame(0);
                int ErrorLine = frame.GetFileLineNumber();
                var Result = _CommonRepository.LogManagement(ControllerName, ActionName, ex.Message, ErrorLine, UserID);
                return Json(null);
            }
        }
        #endregion

        #region Bank Anchor List Page
        /// <summary>
        /// Bank listing view
        /// </summary>
        /// <returns></returns>
        /// 
        [JWTAuthorize("Account", "UserLogin")]
        [CustomFilter]
        public IActionResult BankAnchorList()
        {
            return View("BankAnchorListingPage");
        }
        #endregion

        #region Bank SetLimit View
        /// <summary>
        /// listing of BankSetLimit
        /// </summary>
        /// <returns></returns>
        public IActionResult BankSetLimitListing()
        {
            return View("BankSetLimitList");
        }

        #endregion

        #region Bank Limit Anchor List
        /// <summary>
        /// Bank Limit AnchorListing
        /// </summary>
        /// <returns></returns>
        /// 
        [JWTAuthorize("Account", "UserLogin")]
        [CustomFilter]

Finocart.Web/Controllers/DisbursementController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace Finocart.Web.Controllers
{
    public class DisbursementController : Controller
    {
        /// <summary>
        /// Payment disbursement view
        /// </summary>
        /// <returns></returns>
        public IActionResult PaymentDisbursement()
        {
            try
            {
                return View("PaymentDisbursementList");
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
    }
}

Finocart.Web/Views/BankCompany/BankLimitAnchorListing.cshtml
@{
    ViewData["Title"] = "BankLimitAnchorList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/BankCompany/BankLimitAnchorList.js"></script>
<script>
    var GetBankLimitAnchorList = '@Url.Action("GetBankLimitAnchorList", "BankCompany")';
</script>
<div class="main-inner-section">
    <div class="content-upper-section">
        <div class="tabsec-main">
            <div class="tab-content">
                <div id="eInvoices" class="tab-pane fade in active">
                    <div class="row" id="eAnchorCompInvoices">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="search-box-main clearfix">                               
                                <h4 style="font-size:15px;font-weight:bold;">LIMIT</h4>
                                <div class="col-xs-12 col-sm-4 col-md-4 padding">
                                    @Html.TextBox("txt_AnchorNameSearch", null, new { placeholder = "Search by Anchor Name", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                </div>

                                <div class="col-xs-12 col-sm-8 col-md-8 padding">
                                    <button id="ExportAnchCompCSV" class="excelbutton" style="margin-right:0;">
                                        <img src="~/Content/images/excelicon.png" title="Download Excel File" class="img-responsive" style="display: inline;" />
                                    </button>

                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="main-table-box page-scroll">
                                <div class="table-responsive">
                                    <table id="tbl_BankLimitAnchorList" class="table table-responsive table-hover table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Anchor Name</th>
                                                <th>Contact Name</th>
                                                <th>Anchor Email</th>
                                                <th>Contact Number</th>
                                                @*<th>Available Limits (INR)</th>
                                                <th>Utilized Limits (INR)</th>
                                                <th>ODBD</th>
                                                <th>Interest Rate (% P.A.)</th>
                                                <th>Validity From Date</th>
                                                <th>Validity Upto</th>*@
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>

</div>

Finocart.Web/Views/BankCompany/BankSetLimitList.cshtml
@{
    ViewData["Title"] = "BankSetLimit";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<style>
    
    .charts-section .charts-title {
        position: relative;
        overflow: hidden;
        background-color: #454545;
        padding: 13px 10px 10px 10px;
        border: 1px solid #ececec;
        border-bottom: 1px solid #a2a2a2;
        width: 100%;
    }

    .charts-title .form-control-graph {
        width: 130px;
        padding: 4px;
        font-size: 14px;
        color: #ffffff;
        margin-left: 5px;
        background-color: #a2a2a2;
        outline: none;
        border: 1px solid #fff;
        height: 30px;
        line-height: 36px;
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        border-radius: 0;
    }

    .charts-section .charts-title h5 {
        display: table;
        float: left;
        margin: 0;
        line-height: 2;
        color: #ffffff;
        text-transform: capitalize;
        font-weight: 600;
    }

    .charts-section .chart-div {
        height: 315px;
        text-align: center;
        border: 1px solid #ececec;
        font-weight: bold;
        background-color: #454545;
        color: #ffffff;
        padding-top: 15px;
        border-top: 0;
        width: 100%;
        margin-bottom: 20px;
        overflow: hidden;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="~/BankCompany/BankSetLimit.js"></script>
<script>
    var GetBankSetLimitList = '@Url.Action("GetBankSetLimitList", "BankCompany")';
</script>


<div class="main-inner-section">
    <div class="content-upper-section">
        <div class="tabsec-main">
            <div class="tab-content">
                <div id="eInvoices" class="tab-pane fade in active">
                    <div class="row" id="eAnchorCompInvoices">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="search-box-main clearfix">
                                <div class="col-xs-12 col-sm-4 col-md-4 padding">
                                    @Html.TextBox("txt_CompanyNameSearch", null, new { placeholder = "Search by Anchor Name", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                </div>

                                <div class="col-xs-12 col-sm-4 col-md-4 padding">
                                    <button id="ExportAnchCompCSV" class="excelbutton" style="margin-right:0;">
                                        <img src="~/Content/images/excelicon.png" title="Download Excel File" class="img-responsive" style="display: inline;" />
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="main-table-box page-scroll">
                                <div class="table-responsive">
                                    <table id="tbl_BankSetLimitList" class="table table-responsive table-hover table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Anchor Name</th>
                                                <th>Anchor Email</th>
                                                <th>Avalaible Limits (INR)</th>
                                                <th>Utilized Limits (INR)</th>
                                                <th>Intrest Rate (% P.A.)</th>
                                                <th>Validity From Date</th>
                                                <th>Validity Upto</th>
                                                <th>Modify Limits</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>

</div>

Finocart.Web/Views/BankCompany/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
<script src="~/Scripts/fusioncharts.js"></script>
<script src="~/Scripts/fusioncharts.theme.fusion.js"></script>
<script type="text/javascript"
        src="https://rawgit.com/fusioncharts/fusioncharts-jquery-plugin/develop/dist/fusioncharts.jqueryplugin.min.js"></script>

<style>


    .charts-section .charts-title {
        position: relative;
        overflow: hidden;
        background-color: #454545;
        padding: 13px 10px 10px 10px;
        border: 1px solid #ececec;
        border-bottom: 1px solid #a2a2a2;
        width: 100%;
    }

    .charts-title .form-control-graph {
        /*width: 130px;*/
        padding: 4px;
        font-size: 14px;
        color: #ffffff;
        margin-left: 5px;
        background-color: #a2a2a2;
        outline: none;
        border: 1px solid #fff;
        height: 30px;
        line-height: 36px;
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        border-radius: 0;
    }

    .charts-section .charts-title h5 {
        display: table;
        float: left;
        margin: 0;
        line-height: 2;
        color: #ffffff;
        text-transform: capitalize;
        font-weight: 600;
    }

    .charts-section .chart-div {
        height: 315px;
        text-align: center;
        border: 1px solid #ececec;
        font-weight: bold;
        background-color: #454545;
        color: #ffffff;
        padding-top: 15px;
        border-top: 0;
        width: 100%;
        margin-bottom: 20px;
        overflow: hidden;
    }

    .cls-error {
        display: block;
        color: red;
    }
</style>

<script src="~/BankCompany/BankSetLimitgraph.js"></script>
@*<script>
   var GetTopAnchorCompList = '@Url.Action("GetDiscAnchorCompList", "AnchorCompany")';
</script>*@

<div class="row">
    <h4 style="margin-left:13px;font-size:15px;font-weight:bold;">Dashboard</h4>
    @*<div class="charts-section">*@
        <div class="top-boxes clearfix anchor">
            <div class="col-xs-12 col-sm-6 col-md-2">
                <a href="#" onclick="location.href='@Url.Action("BankAnchorList","BankCompany")'">
                <div class="box1">
                    <h4 style="font-size:20px !important;margin-bottom: 5px;">
                        @*<img src="~/Content/images/box-1.png" class="img-responsive" />*@
                        <p>New Anchors</p>
                    </h4>
                    <h4>@ViewData["TOTALNEWANCHOR"]</h4>
                </div>
                </a>

            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <a href="#" onclick="location.href='@Url.Action("AwaitedInvoiceApproval","AnchorCompDashboard")'">
                    <div class="box2">
                        <h4 style="font-size:20px !important;margin-bottom: 5px;">
                            @*<img src="~/Content/images/box-2.png" class="img-responsive" />*@
                            <p>Existing Anchors</p>

                        </h4>
                        <h4>@ViewData["TOTALEXISTINGANCHOR"]</h4>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">

                <a href="#" onclick="location.href='@Url.Action("BankLimitAnchorListing","BankCompany")'">
                    <div class="box3">
                        <h4 style="font-size:20px !important;margin-bottom: 5px;">
                            @*<img src="~/Content/images/box-3.png" class="img-responsive" />*@
                            <p>Total Set limit</p>
                        </h4>
                        <h4>@ViewData["TOTALBANKLIMITANCHORLIST"]</h4>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">

                <a href="#" onclick="location.href='@Url.Action("DisbursementsListing","BankCompany")'">
                    <div class="box4">
                        <h4 style="font-size:20px !important;margin-bottom: 5px;">
                            @*<img src="~/Content/images/box-3.png" class="img-responsive" />*@
                            <p>Total Disbersement limit</p>
                        </h4>
                        <h4>@ViewData["TOTALUTILIZEDBANKLIMIT"]</h4>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">

                <a href="#" onclick="location.href='@Url.Action("KycUploadListdata","BankCompany")'">
                    <div class="box3">
                        <h4 style="font-size:20px !important;margin-bottom: 5px;">
                            @*<img src="~/Content/images/box-3.png" class="img-responsive" />*@
                            <p>Total Pending KYC</p>
                        </h4>
                        <h4>@ViewData["TOTALPENDINGKYC"]</h4>
                    </div>
                </a>
            </div>
        </div>
    @*</div>*@
    @*<div class="col-xs-12 col-sm-6 col-md-6">*@
        <label style="margin: 0 0 7px 0; font-weight: 600;color: #222;">
            Disbursement Request Received Today INR <span>@ViewBag.requestAmountReceiveToday</span>
        </label>
        <span style="float:right;"><a href="~/BankCompany/BankAnchorList" id="btnSetLimitList" class="dowte">Set Limit</a></span>
        <div class="col-xs-12 col-sm-6 col-md-6 charts-section">
            <div class="charts-title">
                <!-- Select Div Start -->
                <div class="row">
                    <div class="col-md-3">
                        <h5>Clash Flow</h5>
                    </div>
                    <div class="col-md-9 zindex5">
                        <div class="form-inline rightAlign">
                            <div class="form-group" style="float:right;">

                                <select id="SetLimitforAnchor" class="form-control-graph"></select>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!-- Select Div End -->
            </div>
            <div id="chart-container"></div>
        </div>
           
        @*</div>*@
    <div class="col-xs-12 col-sm-6 col-md-6" style="padding-right:0;">
        <h4 style="margin-top: 0;font-size: 12px;">Top Customers (Anchor Companies) <span style="float:right;">3 Months</span></h4>
        <div class="bottom-listing">
            <div class="main-table-box page-scroll ten-tab-scroll">
                <div class="table-responsive">
                    <table id="tbl_TopAnchorCompany" class="table table-responsive table-bordered table-hover internalusermtable">
                        <thead>
                            <tr>
                                <th>Anchor Name</th>
                                <th>Anchor ID</th>
                                <th>Limit Available (INR)</th>
                                <th>Limit Utilize (INR)</th>
                            </tr>

                        </thead>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

<!--Rule of Engine Model Popup-->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog addengine">

        <!-- Modal content-->
        <form>
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close new-close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Rule of Engine</h4>
                </div>
                <div class="modal-body engine-box">
                    <div class="form-group">
                        <input type="text" id="rule_percentage" name="model_popup" placeholder="Enter Percentage" onkeypress="return isNumberKey(event)" class="form-control" />
                        <label id="lblrule_percentageError" class="error" style="color:red;display: none;">Please Enter Value</label>
                    </div>
                    <div class="form-group">
                        <input type="text" id="rule_limit" name="model_popup" placeholder="Enter Limit/Day" onkeypress="return isNumberKey(event)" class="form-control" />
                        <label id="lblrule_limitError" class="error" style="color:red;display: none;">Please Enter Value</label>
                        <label id="lblrule_limitError_radio" class="error" style="color:red;display: none;">Please Select Value</label>
                    </div>
                    <div class="form-group">
                        <label><input style="vertical-align: bottom;margin-right: 5px;" type="radio" name="status" value="yes" id="status_yes">Yes</label>
                        <label><input style="vertical-align: bottom;margin-right: 5px;" type="radio" name="status" value="no" id="status_no">No</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-close" data-dismiss="modal" style="margin:0;">Close</button>
                    <button type="button" class="btn confirmbutton" id="submit_rule_engine">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/BankCompany/BankDashboard.js"></script>

<script>
    $(document).ready(function () {

        $('#tbl_TopAnchorCompany').dataTable({

            "processing": true,
            "serverSide": true,

            "dom": '"ltipr"',
            "scrollX": false,

            "ajax": {
                "url": "../BankCompany/GetTopAnchorData",
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                { "data": "anchor_Name", "name": "anchor_Name", "autoWidth": true }, //index 1
                { "data": "anchor_id", "name": "anchor_id", "autoWidth": true }, //index 2
                { "data": "available_Limits", "name": "available_Limits", "autoWidth": true, render: $.fn.dataTable.render.number(',', '.', 0) }, //index 3
                { "data": "utilized_Limits", "name": "utilized_Limits", "autoWidth": true, render: $.fn.dataTable.render.number(',', '.', 0) } //index 4


            ],
        });
    });
</script>

Finocart.Web/Views/BankCompany/DrawFundsDocumentView.cshtml
@model Finocart.CustomModel.GetDocument_Download
@{
    ViewData["Title"] = "DrawFundsHistoryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .modal-dialog {
        width: 600px;
        margin: 30px auto;
    }

    .hide_column {
        display: none;
    }
</style>
<a class="backbtn" href="javascript:history.back()"><i class="fas fa-long-arrow-alt-left" title="Go Back"></i></a>
<script src="~/BankCompany/DrawFundsDocumentView.js"></script>
<script>
    var DrawFundsDocumentView = '@Url.Action("DrawFundsDocumentViewList", "BankCompany")'
    var Document_download = '@Url.Action("Document_download", "BankCompany")'
</script>
<div class="main-inner-section">
    <div class="content-upper-section" id="AnchorCompany">
        <div class="tabsec-main">
            <div class="tab-content">
                <div class="row" id="">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="main-table-box page-scroll" style="padding:15px;">
                            <h4 style="font-size:15px;font-weight:bold;">Document Download</h4>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="main-table-box page-scroll">
                            <div class="table-responsive">
                                @Html.HiddenFor(m => m.ID)
                                <table id="DrawFundsDocumentView" class="table table-responsive table-hover table-bordered tbl_UserList dataTable no-footer">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>File Name</th>
                                            <th style="width:10%">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>