Finocart.Web/Controllers/VendorController.cs
using Finocart.Interface;
using Finocart.Model;
using Finocart.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Finocart.CustomModel;
using System.Linq;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Finocart.Web.Views.Common;

namespace Finocart.Web.Controllers
{

    
    public class VendorController : BaseController
    {
        #region Interface declaration

        /// <summary>
        /// Lookup data Repository
        /// </summary>
        private readonly ILookupDetails _lookUpRepository;
        /// <summary>
        /// Common Repository
        /// </summary>
        private readonly ICommon _CommonRepository;
        /// <summary>
        ///Vendor Repository
        /// </summary>
        private readonly IVendor _VendorRepository;
        /// <summary>
        /// Configuration
        /// </summary>
        private readonly IConfiguration _configurationRepository;
        /// <summary>
        ///Anchor Company Repository
        /// </summary>
        private readonly IAnchorCompany _AnchorCompanyRepository;
        /// <summary>
        /// Invoice Repository
        /// </summary>
        private readonly IInvoice _invoiceRepository;

        /// <summary>
        /// User data Repository
        /// </summary>
        //private readonly IUser _Userepository;
        #endregion

        #region Constructor 

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="UserRepository"></param>
        public VendorController(ILookupDetails lookupDetailsRepository, ICommon CommonRepository, IVendor vendorRepository, IConfiguration configurationRepository, IInvoice invoiceRepository, IAnchorCompany AnchorCompanyRepository)
        {
            _lookUpRepository = lookupDetailsRepository;
            _CommonRepository = CommonRepository;
            _VendorRepository = vendorRepository;
            _configurationRepository = configurationRepository;
            _AnchorCompanyRepository = AnchorCompanyRepository;
            _invoiceRepository = invoiceRepository;
        }


        #endregion
        /// <summary>
        /// Vendor dashboard view
        /// </summary>
        /// <returns></returns>
        public IActionResult VendorDashboard()
        {
            string ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            string ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            Int32? UserID = HttpContext.Session.GetInt32("UserID");
            string ErrorMessage = string.Empty;

            try
            {
                var Res = _CommonRepository.AuditTrailLog("Select Invoice", "Eligibal Invoice ", UserID, 0);
                Int32? VendorId = HttpContext.Session.GetInt32("CompanyID");
                ViewBag.MaxAvailableAmount = _invoiceRepository.GetMaxAvailableAmount(VendorId);
            }
            catch (Exception ex)
            {
                var st = new StackTrace(ex, true);
                var frame = st.GetFrame(0);
                int ErrorLine = frame.GetFileLineNumber();
                var Result = _CommonRepository.LogManagement(ControllerName, ActionName, ex.Message, ErrorLine, UserID);
                return RedirectToAction("ErrorPage", "Common");
            }
            return View("Dashboard");
          

        }

        /// <summary>
        /// Vendor dashboard main view
        /// </summary>
        /// <returns></returns>
        [JWTAuthorize("Account","UserLogin")]
        [CustomFilter]
        public IActionResult VendorDashboardMain()
        {
            string ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            string ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            Int32? UserID = HttpContext.Session.GetInt32("UserID");
            string ErrorMessage = string.Empty;
            try
            {
                var Res = _CommonRepository.AuditTrailLog("Home", "Vendor Dashbord main", UserID, 0);
                Int32? VendorId = HttpContext.Session.GetInt32("CompanyID");
                string amount= _invoiceRepository.GetMaxAvailableAmount(VendorId);
                // ViewBag.MaxAvailableAmount = _invoiceRepository.GetMaxAvailableAmount(VendorId);

                ViewBag.MaxAvailableAmount = Math.Round(Convert.ToDecimal(amount), 0).ToString("N0");
                var start = "0";
                var length = "10";
                //Get Sort columns value
                var sortBy = "CompanyID asc";
                var receieablesortBy = "anchorID asc";
                var sortByawait = "CompanyName asc";
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                var Companyname = "";
                var Approvedamt = "";

                IEnumerable<AvailableFundCompModel> lstPO = _VendorRepository.getAvailableforfundingList(sortBy, pageSize, skip, Companyname, Approvedamt, "Eligible", VendorId);
                 Res = _CommonRepository.AuditTrailLog("Home", "Vendor Dashbord main Top Anchor Comapny", UserID, 0);
                decimal? sumAvailableFundComp = 0;
                for (int i = 0; i < lstPO.Count(); i++)
                {
                    sumAvailableFundComp = Sum(sumAvailableFundComp, lstPO.ElementAt(i).ApprovedAmt);

                }
                String temp0 = String.Format("{0:C0}", sumAvailableFundComp);
                temp0 = temp0.Replace("$", "");
                if (Convert.ToString(sumAvailableFundComp).Contains("."))
                {
                    string[] values0 = Convert.ToString(sumAvailableFundComp).Split('.');
                  
                    TempData["AVAILABLEFORFUNDINGTODAY"] = temp0;
                }
                else
                {
                    TempData["AVAILABLEFORFUNDINGTODAY"] = temp0;
                }
                IEnumerable<DiscountOfferedInvModel> lstPO1 = _VendorRepository.getInvoicetodaysList(sortBy, pageSize, skip, Companyname, Approvedamt, VendorId);
                Res = _CommonRepository.AuditTrailLog("Home", "Vendor Dashbord main Amount Approve today", UserID, 0);
                decimal? SumAVAILABLEFORFUNDINGTODAY = 0;
                for (int i = 0; i < lstPO1.Count(); i++)
                {
                    SumAVAILABLEFORFUNDINGTODAY = Sum(SumAVAILABLEFORFUNDINGTODAY, lstPO1.ElementAt(i).ApprovedAmt);

                }
                String temp2 = String.Format("{0:C0}", SumAVAILABLEFORFUNDINGTODAY);
                temp2 = temp2.Replace("$", "");
                if (Convert.ToString(SumAVAILABLEFORFUNDINGTODAY).Contains("."))
                {
                    string[] values1 = Convert.ToString(SumAVAILABLEFORFUNDINGTODAY).Split('.');
                   
                    TempData["AMOUNTAPPROVEDTODAYININR"] = temp2;
                }
                else
                {
                    TempData["AMOUNTAPPROVEDTODAYININR"] = temp2;
                }

                IEnumerable<AnchorCompListingModel> lstawaitforapproval = _AnchorCompanyRepository.GetAnchorCompListingByVendorId(VendorId, sortByawait, pageSize, skip, "", Companyname, Approvedamt, "DiscInvoicesStatus", 3);
                Res = _CommonRepository.AuditTrailLog("Home", "Vendor Dashbord main Awaited Approval ", UserID, 0);
                decimal? SumAWAITEDAPPROVALININR = 0;
                for (int i = 0; i < lstawaitforapproval.Count(); i++)
                {
                    SumAWAITEDAPPROVALININR = Sum(SumAWAITEDAPPROVALININR, lstawaitforapproval.ElementAt(i).AwaitTotalInvoiceAppAmount);

                }

                String temp1 = String.Format("{0:C0}", SumAWAITEDAPPROVALININR);
                temp1 = temp1.Replace("$", "");
                if (Convert.ToString(SumAWAITEDAPPROVALININR).Contains("."))
                {
                    string[] values = Convert.ToString(SumAWAITEDAPPROVALININR).Split('.');
                    
                    TempData["AWAITEDAPPROVALININR"] = temp1;
                }
                else
                {
                    TempData["AWAITEDAPPROVALININR"] = temp1;
                }


                IEnumerable<RecievableDue> receieabledue = _VendorRepository.GetRecieableduestoday(VendorId, receieablesortBy, pageSize, skip, 0, Companyname, Approvedamt, "Eligible", 2);
                Res = _CommonRepository.AuditTrailLog("Home", "Vendor Dashbord main Reciveable Today  ", UserID, 0);
                decimal? SumRECEIVABLESDUETODAYININR = 0;
                for (int i = 0; i < receieabledue.Count(); i++)
                {
                    SumRECEIVABLESDUETODAYININR = Sum(SumRECEIVABLESDUETODAYININR, receieabledue.ElementAt(i).AmountReceiabletoday);

                }

                
                String temp3 = String.Format("{0:C0}", SumRECEIVABLESDUETODAYININR);
                temp3 = temp3.Replace("$", "");
                if (temp3.Contains("."))
                {
                    string[] values2 = Convert.ToString(SumRECEIVABLESDUETODAYININR).Split('.');
                   
                    TempData["RECEIVABLESDUETODAYININR"] = temp3;
                }
                else
                {
                    TempData["RECEIVABLESDUETODAYININR"] = temp3;
                }

                var lstHolidays = _VendorRepository.GetHolidayDates();
                if (lstHolidays.Count() > 0)
                {
                    ViewBag.Holidays = string.Join(',',lstHolidays.Select(x => Convert.ToDateTime(x.HolidayDates).ToString("MM/dd/yyyy")).ToArray());
                }
            }
            catch (Exception ex)
            {

Finocart.Web/Views/Vendor/InvoiceHistory.cshtml
@{
    ViewData["Title"] = "Invoice History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Vendor/InvoiceHistory.js"></script>
<style>
    .modal-dialog {
        width: 600px;
        margin: 30px auto;
    }
</style>
<script>
    var GetInvoiceHistory = '@Url.Action("GetInvoiceHistory", "Vendor")';
</script>
<div class="main-inner-section">
    <div class="content-upper-section" id="AnchorCompany">

        <div class="tabsec-main">

            <div class="tab-content">

                <div class="row" id="eAnchorCompInvoices">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="search-box-main clearfix" style="padding: 15px 15px 0;">
                            <h4 style="font-size:15px;font-weight:bold;">Invoices Status (History)</h4>
                            <div class="row">
                                <div class="col-xs-12 col-sm-3 col-md-3">
                                    @Html.DropDownList("pagechange5",new List<SelectListItem>
                                     {
                                      new SelectListItem{ Text="Invoices Status",Value="1"},
                                      new SelectListItem{ Text="Receivables Due Today in INR",Value="2"},
                                      new SelectListItem{ Text="Awaited Approval in INR",Value="3"},
                                      new SelectListItem{ Text="Amount Approved Today in INR",Value="4"},
                                      new SelectListItem{ Text="Available for Funding Today in INR",Value="5"},

                                      }, new { @class = "searchTerm ext-box", @style = "border-right: 1px solid #dadbdc;max-width: 100%;" })
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-3">
                                    @Html.TextBox("txt_CompanyName", null, new { placeholder = "Search by Anchor Company Name", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-3">
                                    @Html.TextBox("txt_TotalApprovedINV", null, new { placeholder = "Search by Total Invoice Amount", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                </div>

                                <div class="col-xs-12 col-sm-3 col-md-3">

                                    <button id="ExportAnchCompCSV" class="excelbutton" style="margin-right:0;">
                                        <img src="~/Content/images/excelicon.png" title="Download Excel File" class="img-responsive" style="display: inline;" />
                                    </button>

                                </div>
                                @*<div class="col-xs-12 col-sm-4 col-md-4">
                                    <h6 style="margin: 5px 0 0;font-size:11px;">Invoices Status</h6>
                                </div>*@
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="main-table-box page-scroll">
                            <div class="table-responsive">
                                <input type="hidden" id="companyID" />
                                <input type="hidden" id="companyInvoicesID" />
                                <table id="tbl_InvoiceHistory" class="table table-responsive table-hover table-bordered tbl_UserList">
                                    <thead>
                                        <tr>
                                            @*<th><input type="checkbox" id="AnchorComp-select-all" /></th>*@

                                            @*<th>Anchor Company Name</th>*@
                                            <th>PO ID</th>
                                            <th>Inv ID</th>
                                            <th>Inv Date</th>
                                            <th>Inv. Amt(INR)</th>
                                            <th>Inv Approved Amt(INR)</th>
                                            <th>Discount Offered</th>
                                            <th>Discount Offered On</th>
                                            <th>Status</th>
                                            <th>Discount Approved On</th>
                                            <th>Disbursement Amt (Based on Approval T+X)</th>
                                            <th>Discount Amt(INR)</th>
                                            <th>UTR Details if Paid</th>
                                            <th>Finoassist/Select Invoices</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-xs-12 footer-btn">
                            <div class="row">

                                <div class="col-xs-12 col-sm-12">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-4 padding">
                                            <label class="footer-label">Total Number of Invoices: <span id="lbTotalInvoices"></span></label>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 padding">
                                            <label class="footer-label">Total Invoice Amount (INR): <span id="lbTotalInvoicesAmt"></span></label>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 padding">
                                            <label class="footer-label">Total Invoice Approved Amount (INR): <span id="lbTotalInvoicesAppAmt"></span></label>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
</div>

Finocart.Web/Views/Vendor/InvoiceJourney.cshtml
@model IEnumerable<Finocart.CustomModel.InvoiceJourneyHistoryModel>
@{
    ViewData["Title"] = "InvoiceJourney";
}

<h1>InvoiceJourney</h1>
<div>
    <div>
        @for(var i=0;i<Model.Count();i++)
        {
        <div>

        </div>
        }
    </div>
</div>

Finocart.Web/Views/Vendor/ReceivableDue.cshtml
@model IEnumerable<Finocart.CustomModel.RecievableDue>

@{
    ViewData["Title"] = "ReceivableDue";
}
<script src="~/Vendor/RecieableDue.js"></script>
<script>
    var GetRecieableDueAmount = '@Url.Action("GetRecieableDueAmount","Vendor")';
</script>
<style>
    .modal-dialog {
        width: 600px;
        margin: 30px auto;
    }
</style>
<div class="main-inner-section">
    <div class="content-upper-section" id="AnchorCompany">

        <div class="tabsec-main">
            <div class="tab-content">
                <div id="eInvoices" class="tab-pane fade in active">

                    <div class="row" id="eAnchorCompInvoices">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="search-box-main clearfix" style="padding: 15px 15px 0;">
                                @*-------------------Deepak Savani------------*@
                                <h4 style="font-size:15px; font-weight:bold">Receivables Due Today</h4>
                                @*                               <h4 style="margin-left:3px;font-size:11px; font-weight:bold">Receivables Due Today</h4>*@
                                <div class="row">
                                    <div class="col-xs-12 col-sm-3 col-md-3">
                                        @Html.DropDownList("pagechange2",new List<SelectListItem>
                                         {
                                          new SelectListItem{ Text="Receivables Due Today in INR",Value="1"},
                                          new SelectListItem{ Text="Awaited Approval in INR",Value="2"},
                                          new SelectListItem{ Text="Amount Approved Today in INR",Value="3"},
                                          new SelectListItem{ Text="Available for Funding Today in INR",Value="4"},
                                          new SelectListItem{ Text="Invoices Status",Value="5"}
                                      }, new { @class = "searchTerm ext-box", @style = "border-right: 1px solid #dadbdc;max-width: 100%;" })
                                    </div>
                                    <div class="col-xs-12 col-sm-3 col-md-3">
                                        @Html.TextBox("txt_CompanyName", null, new { placeholder = "Search by Anchor Company Name", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                    </div>
                                    <div class="col-xs-12 col-sm-3 col-md-3">
                                        @Html.TextBox("txt_TotalApprovedINV", null, new { placeholder = "Search by Total Invoice Amount", @class = "searchTerm" })<span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                    </div>
                                    <div class="col-xs-12 col-sm-3 col-md-3">
                                        <button id="ExportAnchCompCSV" class="excelbutton" style="margin-right:0;">
                                            <img src="~/Content/images/excelicon.png" title="Download Excel File" class="img-responsive" style="display: inline;" />
                                        </button>

                                    </div>
                                    <div class="clearfix"></div>
                                    @*------Deepak Savani-----*@
                                    @*<div class="col-xs-12 col-sm-4 col-md-4">
                                            <h6 style="margin: 5px 0 0;font-size:11px;font-weight:bold">Anchor Companies wise Receivables Due Today</h6>
                                        </div>*@
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="main-table-box page-scroll">
                                <div class="table-responsive">
                                    <input type="hidden" id="anchorID" />
                                    <input type="hidden" id="companyInvoicesID" />
                                    <table id="tbl_AnchorCompList" class="table table-responsive table-hover table-bordered tbl_UserList">
                                        <thead>
                                            <tr>
                                                @*<th><input type="checkbox" id="AnchorComp-select-all" /></th>*@
                                                <th hidden>Anchor Comp ID</th>
                                                <th>Anchor Comp Name</th>
                                                <th>No. of Disc. Accepted Inv</th>
                                                <th>Total Inv. Amt (INR)</th>
                                                <th>Total Approved Amt (INR)</th>
                                                <th>Amt Receivable Today (INR)</th>
                                                <th style="width:10%">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-xs-12 footer-btn">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12">
                                        <div class="row">
                                            <div class="col-xs-12 col-sm-4 padding">
                                                <label class="footer-label">Total Number of Approved Invoices: <span id="lblapprovedinvices"></span></label>
                                            </div>
                                            <div class="col-xs-12 col-sm-4 padding">
                                                <label class="footer-label">Total Approved Amount (INR): <span id="lblapprovedamount"></span></label>
                                            </div>
                                            <div class="col-xs-12 col-sm-4 padding">
                                                <label class="footer-label">Total  Amount Receivable Today (INR): <span id="lblamountrecievabletoday"></span></label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="dInvoices" class="tab-pane fade">
                    <div class="row" id="dOfferedInvoices">
                    </div>
                </div>
                <div id="dBucketInvoices" class="tab-pane fade">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="search-box-main clearfix">
                                <input type="hidden" id="MaxSearchLimit" value="@TempData["MaxSearchCount"]" />
                                <div class="col-xs-12 col-sm-4 col-md-4 padding">
                                    <input type="text" class="searchTerm" id="txt_AnchorName" placeholder="Search by Total Invoice Amount" /><span class="searchButton"><img src="~/Content/images/searchicon.png" class="img-responsive" style="display: inline;" /></span>
                                </div>

                                <div class="col-xs-12 col-sm-3 col-md-3 padding">
                                    <button id="ExportDiscBucketWiseCSV" class="excelbutton">
                                        <img src="~/Content/images/excelicon.png" title="Download Excel File" class="img-responsive" style="display: inline;" />
                                    </button>
                                    <button id="btnDiscBuckFilter" class="filterbtn">
                                        <img src="~/Content/images/filtericon.png" title="Filter" class="img-responsive" />
                                    </button>
                                </div>

                            </div>
                            <div class="search-box-main clearfix" id="dvMainlstSrch">
                                <div class="col-xs-12 padding" id="dvlstSrch">
                                    Recent Searches <i class="fas fa-long-arrow-alt-right" style="margin-right:10px;"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Finocart.Web/Views/Vendor/SelectInvoiceManual.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

Finocart.Web/Views/Vendor/UploadVendorDocuments.cshtml
@model IEnumerable<Finocart.Model.LookupDetails>
@{
    ViewData["Title"] = "UploadDocuments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    var DeleteVendorDoc="@Url.Action("DeleteVendorDoc", "Vendor")";
</script>
<div class="main-inner-section">
    <div class="content-upper-section">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="main-head">
                    <h2>Upload Documents</h2>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="main-content-box page-scroll">
                    <div class="up-tab-head">
                        <h2>Upload Supporting Documents for your vendor</h2>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <label>Attachment Type<span style="color:red;">*</span></label>
                            <div class="">
                                <select name="documentname" class="form-control" id="selUpDoc">
                                    <option value=0>Select Document Name</option>
                                    @foreach (var item in Model)
                                    {
                                        <option value='@item.Id'>@item.LookupValue</option>
                                    }
                                </select>
                                <label id="lblDocTypeError" class="error" style="color:red;display: none;">Select document type</label>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <label>Document File Name</label>
                            <div class="row">
                                <div class="col-xs-12 docupload form-group">
                                    <label>Choose file<input type="file" id="myfile" name="AnchorDocument" size="60"></label>
                                    <button class="upload-btn" type="submit" id="" onclick="uploadcsvfile()"><img src="~/Content/images/upload.png" class="img-responsive" /></button>
                                </div>
                                <div class="col-xs-12">
                                    <p style="font-size:11px;margin-bottom:15px;">
                                        Please Upload Self Attested Scanned Copy (Only PDF) of supporting
                                        documents
                                    </p>
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="Vendoruploaddocuments" class="table table-responsive table-hover table-bordered uploaddocuments">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Document Type</th>
                                    <th>Document Description (File Name)</th>
                                    <th>Status</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Vendor/Vendor.js"></script>
<script src="~/Common/Common.js"></script>
<script type="text/javascript">
    function uploadcsvfile() {
        if ($("#selUpDoc").val() == 0) {
            $("#lblDocTypeError").show();
        }
        var formData = new FormData();
        formData.append('VendorDocument', $('#myfile')[0].files[0]);
        formData.append('iDocumentTypeID', $("#selUpDoc").val());
        $.ajax({
            url: "/Vendor/UploadFileDatatoServer/",
            type: "POST",
            dataType: "json",
            data: formData,
            contentType: false,
            processData: false,
            success: function (data) {
                

                if (data.bResult == true) {
                    Common.CustomSuccessNotify("Vendor document uploaded");
                    location.reload();
                }
                else {
                    Common.CustomErrorNotify(data.ReturnMessage);
                    location.reload();
                }
            },
            error: function (data) {

            }
        })
    }
</script>